/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const LinkScraper = t.union(t.iface([], {
  "strategy": t.lit('simple'),
  "scraperConfig": t.iface([], {
    "containerSelector": "string",
    "linkSelector": "string",
  }),
}), t.iface([], {
  "strategy": t.lit('paginateURL'),
  "scraperConfig": t.iface([], {
    "containerSelector": "string",
    "linkSelector": "string",
    "nextPageQueryParam": "string",
    "startingPage": t.opt("number"),
    "delta": t.opt("number"),
    "waitMs": t.opt("number"),
  }),
}), t.iface([], {
  "strategy": t.lit('paginateButton'),
  "scraperConfig": t.iface([], {
    "containerSelector": "string",
    "linkSelector": "string",
    "nextPageButtonSelector": "string",
    "waitMs": t.opt("number"),
  }),
}), t.iface([], {
  "strategy": t.lit('infiniteScroll'),
  "scraperConfig": t.iface([], {
    "containerSelector": "string",
    "linkSelector": "string",
    "scrollCount": "number",
  }),
}));

export const ScraperInstructions = t.iface([], {
  "url": "string",
  "linkScraper": "LinkScraper",
  "contentScraper": t.iface([], {
    "contentElements": t.array(t.iface([], {
      "required": t.opt("boolean"),
      "selector": "string",
      "label": t.opt("string"),
      "skipFront": t.opt("number"),
      "skipBack": t.opt("number"),
      "normalize": t.opt("boolean"),
      "trimAfter": t.opt(t.union("string", t.array("string"))),
      "multiple": t.opt("boolean"),
      "flatten": t.opt("boolean"),
    })),
    "imageSelector": t.opt("string"),
  }),
  "metadata": t.iface([], {
    [t.indexKey]: "any",
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  LinkScraper,
  ScraperInstructions,
};
export default exportedTypeSuite;
